# Generated by Django 3.2.5 on 2021-07-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('color', models.CharField(max_length=64)),
                ('memory', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/phones')),
            ],
        ),
    ]
