# Generated by Django 3.2.5 on 2021-07-21 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_watch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='memory',
        ),
    ]
