# Generated by Django 3.2.5 on 2021-07-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_watch_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='description',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='description',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
    ]
