# Generated by Django 3.2.5 on 2021-07-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='category',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='category',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='category',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
