# Generated by Django 3.2.5 on 2021-07-24 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_auto_20210724_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.category'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.category'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.category'),
        ),
    ]
