# Generated by Django 3.2.5 on 2021-07-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_auto_20210724_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='on_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phone',
            name='on_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watch',
            name='on_main',
            field=models.BooleanField(default=False),
        ),
    ]
